extends:
  - eslint:recommended
  - plugin:vue/essential

parserOptions:
  sourceType: module
  ecmaVersion: 8

env:
  browser: true
  es6: true
  node: true

rules:
  strict:
    - error
    - global
  indent:
    - error
    - 2
  semi: error
  quotes:
    - error
    - single
